spring:
  datasource:
    url: jdbc:postgresql://database-1.cwcnxw82qp5m.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: mahipalyadav
  
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
     ddl-auto: create
     