spring:
  datasource:
  
   url: jdbc:postgresql://database-1.cwcnxw82qp5m.us-east-1.rds.amazonaws.com:5432/postgres
   username: postgres
   password: mahipalyadav
  
  jpa:
   show-sql: true
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   hibernate:
      ddl-auto: create
